version: 0.2
phases:
  install:
    commands:
      - curl -fsSLo /tmp/terraform.zip "https://releases.hashicorp.com/terraform/${TF_VERSION}/terraform_${TF_VERSION}_linux_amd64.zip"
      - unzip -q /tmp/terraform.zip -d /usr/local/bin
  pre_build:
    commands:
      - terraform -chdir=infra init -input=false -backend-config="bucket=${TF_STATE_BUCKET}"
      - terraform -chdir=infra validate
  build:
    commands:
      - terraform -chdir=infra apply -input=false -auto-approve
      - terraform -chdir=infra output -json > /tmp/infra-outputs.json
artifacts:
  files:
    - /tmp/infra-outputs.json
  discard-paths: yes
